Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name, email and UFID.
Please do not modify instruction cells or any cells with automated tests (marked with `[ASSERTS]`). Note: you can add new cells if you need them, but answers must be in the cells with `YOUR CODE HERE` or "YOUR ANSWER HERE" comments.

---

# Homework 0: Setting Up Your Environment!

## Preamble: Write your Name, Email and UFID

In [1]:
NAME = 'Kondreddy Rohith Sai Reddy'
EMAIL = 'r.kondreddy@ufl.edu'
UFID = 65682267

# YOUR CODE HERE
# raise NotImplementedError()

In [2]:
""" [ASSERTS] Check that your name, email, and UFID is filled in."""
assert NAME != '' and NAME != 'Your name here.' and len(NAME) > 3
assert EMAIL != '' and EMAIL != 'Your email here.' and len(EMAIL) > 7
assert type(UFID) == int and UFID != 12345678 and UFID >= 10000000 and UFID <= 99999999

## Academic Integrity

### <span style="color:red;">This is an individual assignment. Academic integrity violations (i.e., cheating, plagiarism) will be reported to SCCR!</span><br/>
#### The official CISE policy recommended for such offenses is a course grade of E. Additional sanctions may be imposed by SCCR such as marks on your permanent educational transcripts, dismissal or expulsion.
#### Reminder of the Honor Pledge: On all work submitted for credit by Students at the University of Florida, the following pledge is either required or implied: *"On my honor, I have neither given nor received unauthorized aid in doing this assignment."*

#### Acknowledgement: Do you acknowledge and understand the academic integrity warning above? 

In [3]:
# YOUR CODE HERE
academic_integrity_acknowledgement = True
# raise NotImplementedError()

In [4]:
""" [ASSERTS] Check that you acknowledge the academic integrity warning, you understanding it and have been reminded of the UF Honor Pledge."""
assert academic_integrity_acknowledgement

---
# [Task 1] Check that the cell below runs with no errors and that the version of Python is at least 3.8 and the version of Tensorflow is at least 2.1!

In [5]:
# Load packages we need
import sys
import os

import numpy as np
import scipy as sp
import pandas as pd

import sklearn

import matplotlib 

import tensorflow as tf

# Let's check our software versions
print('### Python version: ' + sys.version)
print('### Numpy version: ' + np.__version__)
print('### Scipy version: ' + sp.__version__)
print('### Pandas version: ' + pd.__version__)
print('### Scikit-learn version: ' + sklearn.__version__)
print('### Matplotlib version: ' + matplotlib.__version__)
print('### TensorFlow version: ' + tf.__version__)
print('------------')

### Python version: 3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)]
### Numpy version: 1.26.3
### Scipy version: 1.11.4
### Pandas version: 2.1.4
### Scikit-learn version: 1.3.2
### Matplotlib version: 3.8.2
### TensorFlow version: 2.15.0
------------


### [Task 1] (15 Points) Paste in the cell below the output of the cell above (with the library versions)!

In [6]:
# Paste the output here:
#
#
# YOUR CODE HERE
### Python version: 3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)]
### Numpy version: 1.26.3
### Scipy version: 1.11.4
### Pandas version: 2.1.4
### Scikit-learn version: 1.3.2
### Matplotlib version: 3.8.2
### TensorFlow version: 2.15.0


print("### Python version: 3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)]")
print("### Numpy version: 1.26.3")
print("### Scipy version: 1.11.4")
print("### Pandas version: 2.1.4")
print("### Scikit-learn version: 1.3.2")
print("### Matplotlib version: 3.8.2")
print("### TensorFlow version: 2.15.0")

# raise NotImplementedError()

### Python version: 3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)]
### Numpy version: 1.26.3
### Scipy version: 1.11.4
### Pandas version: 2.1.4
### Scikit-learn version: 1.3.2
### Matplotlib version: 3.8.2
### TensorFlow version: 2.15.0


In [7]:
""" [ASSERTS] Check environment and versions."""
python_ver_split = sys.version.split('.')
assert int(python_ver_split[0]) >= 3 and int(python_ver_split[1]) >= 8
tf_ver_split = tf.__version__.split('.')
assert int(tf_ver_split[0]) >= 2 and int(tf_ver_split[1]) >= 1

---
# [Task 2] (10 Points) Tell us a little bit about yourself and what you hope to learn in this course

## [Task 2a] (5 Points) Write a brief description of your academic history (2-3 sentences is fine)

In [8]:
# YOUR CODE HERE
print("I earned my Bachelor of Technology in Information Technology from Vellore Institute of Technology, India, achieving a GPA of 3.77/4.0. Currently, I am pursuing a Master of Science in Computer Science at the University of Florida, USA, where I am delving into courses such as Analysis of Algorithms and Advanced Data Structures.")
# raise NotImplementedError()

I earned my Bachelor of Technology in Information Technology from Vellore Institute of Technology, India, achieving a GPA of 3.77/4.0. Currently, I am pursuing a Master of Science in Computer Science at the University of Florida, USA, where I am delving into courses such as Analysis of Algorithms and Advanced Data Structures.


## [Task 2b] (5 Points) Briefly describe what you hope to learn in this course (a few sentences is fine)

In [9]:
# YOUR CODE HERE

print("In this course, I aim to gain a comprehensive understanding of machine learning engineering. Specifically, I hope to delve into topics such as NumPy, SciPy, Matplotlib Basics, linear models, regression, regularization, logistic regression, SVM, decision trees, ensemble methods, model performance evaluation, gradient descent, neural networks, convolutional neural networks, autoencoders, generative adversarial networks, and various other advanced concepts. Additionally, I look forward to developing practical skills through exercises and hands-on projects, enhancing my ability to apply machine learning techniques in real-world scenarios.")
# raise NotImplementedError()

In this course, I aim to gain a comprehensive understanding of machine learning engineering. Specifically, I hope to delve into topics such as NumPy, SciPy, Matplotlib Basics, linear models, regression, regularization, logistic regression, SVM, decision trees, ensemble methods, model performance evaluation, gradient descent, neural networks, convolutional neural networks, autoencoders, generative adversarial networks, and various other advanced concepts. Additionally, I look forward to developing practical skills through exercises and hands-on projects, enhancing my ability to apply machine learning techniques in real-world scenarios.


---
# [Task 3] (25 Points) Familiarize yourself with Python and NumPy and write some code to demonstrate your understanding. (Note: the basics notebook is a great resource!)

## [Task 3a] (5 Points) Create a numpy array 'a' that contains the integers 0 to 10. The shape of it should be (11,).

In [10]:
"""Put your code to create 'a' here.
"""
# YOUR CODE HERE

a = np.array([0,1,2,3,4,5,6,7,8,9,10])


#or
#a = np.arange(11)

# raise NotImplementedError()

In [11]:
""" [ASSERTS] Check the answer."""
print(a) # this should print: "[ 0 1  2  3  4  5  6  7  8  9 10]"
assert a.shape == (11,)

[ 0  1  2  3  4  5  6  7  8  9 10]


## [Task 3b] (5 Points) Let 'b' be the numpy array where every element is the square of the corresponding element in 'a'. The shape should be (11,).

In [12]:
"""Put your code to create 'b' here.
"""
# YOUR CODE HERE

b = np.square(a)


# raise NotImplementedError()

In [13]:
""" [ASSERTS] Check the answer."""
print(b) # this should print: "[  0   1   4   9  16  25  36  49  64  81 100]"
assert b.shape == (11,)

[  0   1   4   9  16  25  36  49  64  81 100]


## [Task 3c] (5 Points) Create an 3x4 numpy array 'c' of random integers in [-5, +5[ (use numpy.random.randint).

In [14]:
"""Put your code to create 'c' here.
"""
# YOUR CODE HERE

c = np.random.randint(-5, 5, size=(3, 4))


# raise NotImplementedError()

In [15]:
""" [ASSERTS] Check the answer."""
print(c)
assert c.shape == (3,4)

[[-4 -1 -4  4]
 [-3  0 -3  4]
 [-1  0 -1  4]]


## [Task 3d] (5 Points) Let 'd' be the reshaped version of 'c' as a 6x2 array.

In [16]:
"""Put your code to create 'd' here.
"""
# YOUR CODE HERE


d = c.reshape(6, 2)


# raise NotImplementedError()

In [17]:
""" [ASSERTS] Check the answer."""
print(d)
assert d.shape == (6,2)

[[-4 -1]
 [-4  4]
 [-3  0]
 [-3  4]
 [-1  0]
 [-1  4]]


## [Task 3e] (5 Points) Use numpy or scipy to draw 1000 i.i.d. random samples from the Gaussian distribution with the mean given by the first digit of your UFID and the standard deviation given by the square root of the sum of all digits in your UFID. For example, if you UFID is 2801104 the mean would be 2 and the standard deviation is 4. Let 'e' be the array with the random samples.

In [18]:
"""Put your code to create 'e' here.
"""
# YOUR CODE HERE

# UFID = 65682267

mean_value = int(str(UFID)[0])

std_deviation = 0
for digit in str(UFID):
    std_deviation += int(digit)

std_deviation = np.sqrt(std_deviation)


e = np.random.normal(mean_value, std_deviation, 1000)

print(e)
# raise NotImplementedError()

[ 2.14361593e+01 -4.13890273e+00  2.29173335e+00  1.09096041e+00
  7.84057524e+00  1.05419960e+01  1.10321821e+00  6.50677105e+00
  2.60142915e+00  9.00182094e+00 -7.93202230e+00  3.33723316e+00
  1.29443746e+01  8.17082592e+00  1.45490874e+00 -1.39903664e+01
  7.09576860e-01 -1.21103818e+00  1.09193152e+01  1.61598188e+01
  1.66152871e+01 -5.00805999e-01  6.23049179e+00  1.59725097e+00
  7.37534406e+00  1.69269861e+00 -8.50263865e+00  1.28485356e+01
  3.02288124e+00  6.99828636e+00  6.29433816e-01  4.91326244e+00
  6.46201144e+00  1.01636114e+01  9.11545151e+00  7.00073553e+00
  4.13247106e+00  2.41243243e+01  1.26664201e+00  1.01962990e+01
  1.32597285e+01 -5.18961437e-01  7.56646524e+00  1.09913687e+00
  7.66786182e+00  4.97499005e+00  5.91944431e+00  3.21030131e+00
  9.50633386e+00  1.37916059e+01 -1.64139993e+00 -1.91227318e-01
 -1.69934356e+00  2.23247389e-01 -7.66404564e-01  1.52392604e+00
 -2.92026862e+00 -2.71577671e+00  1.13818773e+01  3.13835422e-01
  4.15810126e+00  6.79314

In [19]:
""" [ASSERTS] Check the answer."""
assert e.shape == (1000,) or e.shape == (1000,1)